parameters:
    main:
        env: 'cartpole'
        obs_size: 4
        rollout_steps: 8
        num_actions: 2
        name: 'environments:cartpole-v0'
        hidden_size: 128
        hidden_size_2: 128
        seq_len: 1
        num_workers: 4
        epsilon: 0.1
        beta: 0.01
        render: False
        policy: 'FNNPolicy'
        framestack: False
        total_steps: 4.0e+5
        eval_steps: 1.0e+4
        eval_freq: 1.0e+4
        render: False
