parameters:
    main:
        env: 'pendulum'
        obs_size: 3
        rollout_steps: 32
        num_actions: 1
        continuous_actions: true
        action_min: -2.0
        action_max: 2.0
        name: 'environments:pendulum-v0'
        hidden_size: 128
        hidden_size_2: 128
        seq_len: 1
        num_workers: 4
        epsilon: 0.1
        beta: 0.01
        render: False
        policy: 'FNNPolicy'
        framestack: False
        total_steps: 4.0e+5
        eval_steps: 4.0e+3
        eval_freq: 1.0e+4
        render: False