parameters:
    main:
        env: 'tmaze'
        obs_size: 26
        rollout_steps: 8
        num_actions: 4
        name: 'tmaze'
        hidden_size: 128
        hidden_size_2: 128
        seq_len: 1
        num_workers: 4
        epsilon: 0.1
        beta: 0.01
        render: False
        policy: 'FNNPolicy'
        load_policy: False
        framestack: False
        total_steps: 1.0e+5
        eval_steps: 1.0e+4
        eval_freq: 1.0e+4
        render: False
